$content = Get-Content 'app.js' -Raw -Encoding UTF8

# Replace placeholder URLs to encode spaces and special characters
$content = $content -replace 'text=nomanssky', 'text=No+Mans+Sky'
$content = $content -replace 'text=bf2042', 'text=Battlefield+2042'
$content = $content -replace 'text=spiderman', 'text=Spider-Man'
$content = $content -replace 'text=fifa23', 'text=FIFA+23'
$content = $content -replace 'text=acvalhalla', 'text=AC+Valhalla'
$content = $content -replace 'text=tlou', 'text=The+Last+of+Us'
$content = $content -replace 'text=ow2', 'text=Overwatch+2'
$content = $content -replace 'text=starfield', 'text=Starfield'
$content = $content -replace 'text=liesp', 'text=Lies+of+P'
$content = $content -replace 'text=sf6', 'text=Street+Fighter+6'
$content = $content -replace 'text=redfall', 'text=Redfall'
$content = $content -replace 'text=hogwarts', 'text=Hogwarts+Legacy'
$content = $content -replace 'text=d4', 'text=Diablo+IV'
$content = $content -replace 'text=re8', 'text=RE+Village'
$content = $content -replace 'text=b4b', 'text=Back+4+Blood'
$content = $content -replace 'text=returnal', 'text=Returnal'
$content = $content -replace 'text=deathloop', 'text=Deathloop'
$content = $content -replace 'text=gotham', 'text=Gotham+Knights'
$content = $content -replace 'text=atomic', 'text=Atomic+Heart'
$content = $content -replace 'text=sifu', 'text=Sifu'
$content = $content -replace 'text=ghostwire', 'text=Ghostwire+Tokyo'
$content = $content -replace 'text=ratchet', 'text=Ratchet+Clank'
$content = $content -replace 'text=kena', 'text=Kena'
$content = $content -replace 'text=saintsrow', 'text=Saints+Row'
$content = $content -replace 'text=gotg', 'text=Guardians+Galaxy'
$content = $content -replace 'text=forspoken', 'text=Forspoken'
$content = $content -replace 'text=plague', 'text=Plague+Tale'
$content = $content -replace 'text=dl2', 'text=Dying+Light+2'
$content = $content -replace 'text=tina', 'text=Tiny+Tinas'
$content = $content -replace 'text=evildead', 'text=Evil+Dead'
$content = $content -replace 'text=stray', 'text=Stray'
$content = $content -replace 'text=vampire', 'text=Vampire+Survivors'
$content = $content -replace 'text=cult', 'text=Cult+of+Lamb'
$content = $content -replace 'text=tunic', 'text=Tunic'
$content = $content -replace 'text=scorn', 'text=Scorn'
$content = $content -replace 'text=nier', 'text=Nier+Automata'
$content = $content -replace 'text=metro', 'text=Metro+Exodus'
$content = $content -replace 'text=quarry', 'text=The+Quarry'
$content = $content -replace 'text=wolong', 'text=Wo+Long'
$content = $content -replace 'text=highonlife', 'text=High+on+Life'
$content = $content -replace 'text=deadspace', 'text=Dead+Space'
$content = $content -replace 'text=remnant2', 'text=Remnant+II'
$content = $content -replace 'text=payday3', 'text=Payday+3'
$content = $content -replace 'text=ac6', 'text=Armored+Core+VI'
$content = $content -replace 'text=cities2', 'text=Cities+Skylines+II'
$content = $content -replace 'text=alanwake2', 'text=Alan+Wake+II'
$content = $content -replace 'text=mk1', 'text=Mortal+Kombat+1'
$content = $content -replace 'text=tcm', 'text=Texas+Chainsaw'
$content = $content -replace 'text=robocop', 'text=Robocop'

Set-Content 'app.js' -Value $content -Encoding UTF8 -NoNewline
Write-Host "Obrázky opraveny!"
